/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ExploreContainer: typeof import('./components/ExploreContainer.vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonListHeader: typeof import('@ionic/vue')['IonListHeader']
    IonMenu: typeof import('@ionic/vue')['IonMenu']
    IonMenuButton: typeof import('@ionic/vue')['IonMenuButton']
    IonMenuToggle: typeof import('@ionic/vue')['IonMenuToggle']
    IonNote: typeof import('@ionic/vue')['IonNote']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSplitPane: typeof import('@ionic/vue')['IonSplitPane']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
